### PR TITLE
Resolved set up Dates correctly #5

### PR DESCRIPTION
**Pull request by dangilkerson**
Use date-fns to format dates

### CODE REVIEW

**Comment by s-Hale** [comment]
Thanks @dangilkerson ! Merge master and I'll get this in :)

**Comment by s-Hale** [comment]
@dangilkerson Still got conflicts.

**Comment by dangilkerson** [comment]
Resolved the conflicts

**Comment by s-Hale** [comment]
@dangilkerson Merged it but it threw a couple errors regarding Invalid Time Range, so reverted it off. If you want to take a look and try again that'd be cool. Do a branch so I can take a look without affecting master, then I'll merge it in if it runs OK.

**Pull request merged**
